import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SOURCE = path.join(ROOT, 'colors_and_type.css');
const OUT_DIR = path.join(ROOT, 'tokens');
const OUT_JSON = path.join(OUT_DIR, 'tokens.json');
const OUT_CSS = path.join(OUT_DIR, 'tokens.css');
const OUT_TS = path.join(OUT_DIR, 'tokens.ts');

const checkOnly = process.argv.includes('--check');

function parseRootVariables(css) {
  const rootStart = css.indexOf(':root');
  if (rootStart < 0) {
    throw new Error('Could not find :root block in colors_and_type.css');
  }

  const openBrace = css.indexOf('{', rootStart);
  if (openBrace < 0) {
    throw new Error('Could not find opening brace for :root block');
  }

  let depth = 1;
  let i = openBrace + 1;
  while (i < css.length && depth > 0) {
    const ch = css[i];
    if (ch === '{') depth += 1;
    if (ch === '}') depth -= 1;
    i += 1;
  }

  const rootBlock = css.slice(openBrace + 1, i - 1);
  const lines = rootBlock.split('\n');
  const vars = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line.startsWith('--of-')) continue;
    const colonIndex = line.indexOf(':');
    const semicolonIndex = line.lastIndexOf(';');
    if (colonIndex < 0 || semicolonIndex < 0) continue;

    const name = line.slice(0, colonIndex).trim();
    const value = line.slice(colonIndex + 1, semicolonIndex).trim();
    vars.push({ name, value });
  }

  return vars;
}

function categoryFromName(name) {
  const bare = name.replace(/^--of-/, '');
  const [head] = bare.split('-');
  const map = {
    magenta: 'color',
    gray: 'color',
    success: 'color',
    warning: 'color',
    danger: 'color',
    info: 'color',
    bg: 'semanticColor',
    fg: 'semanticColor',
    border: 'semanticColor',
    ring: 'semanticColor',
    gradient: 'semanticColor',
    font: 'typography',
    text: 'typography',
    leading: 'typography',
    tracking: 'typography',
    radius: 'radius',
    shadow: 'shadow',
    space: 'spacing',
    ease: 'motion',
    dur: 'motion'
  };
  return map[head] ?? 'other';
}

function buildJson(tokens) {
  const byCategory = {
    color: {},
    semanticColor: {},
    typography: {},
    radius: {},
    shadow: {},
    spacing: {},
    motion: {},
    other: {}
  };

  for (const token of tokens) {
    byCategory[categoryFromName(token.name)][token.name] = token.value;
  }

  return {
    $schema: 'https://opsforward.com/schemas/keel-tokens.schema.json',
    source: 'colors_and_type.css',
    count: tokens.length,
    categories: byCategory
  };
}

function buildCss(tokens) {
  const lines = [];
  lines.push('/* Auto-generated by scripts/export-tokens.mjs. Do not edit directly. */');
  lines.push(':root {');
  for (const token of tokens) {
    lines.push(`  ${token.name}: ${token.value};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function buildTs(jsonObj) {
  return [
    '// Auto-generated by scripts/export-tokens.mjs. Do not edit directly.',
    '',
    `export const keelTokens = ${JSON.stringify(jsonObj, null, 2)} as const;`,
    '',
    'export type KeelTokens = typeof keelTokens;',
    ''
  ].join('\n');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeOrCheck(filePath, content) {
  if (!fs.existsSync(filePath)) {
    if (checkOnly) return false;
    fs.writeFileSync(filePath, content, 'utf8');
    return true;
  }

  const prev = fs.readFileSync(filePath, 'utf8');
  if (prev === content) return true;

  if (checkOnly) return false;
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function main() {
  const sourceCss = fs.readFileSync(SOURCE, 'utf8');
  const tokens = parseRootVariables(sourceCss);

  ensureDir(OUT_DIR);

  const jsonObj = buildJson(tokens);
  const jsonContent = `${JSON.stringify(jsonObj, null, 2)}\n`;
  const cssContent = buildCss(tokens);
  const tsContent = buildTs(jsonObj);

  const okJson = writeOrCheck(OUT_JSON, jsonContent);
  const okCss = writeOrCheck(OUT_CSS, cssContent);
  const okTs = writeOrCheck(OUT_TS, tsContent);

  if (checkOnly) {
    if (!okJson || !okCss || !okTs) {
      console.error('Token artifacts are out of date. Run: npm run tokens:build');
      process.exit(1);
    }
    console.log('Token artifacts are up to date.');
    return;
  }

  console.log(`Exported ${tokens.length} tokens to tokens/`);
}

main();
